### ISSUE TITLE
Update project plan 

### ISSUE THREAD

**Issue by emrehoser** [bounswe/bounswe2020group5#105]

**Comment by misraya** [comment]
We had a meeting on 02.11.20, prepared our [451 project plan.](https://github.com/bounswe/bounswe2020group5/tree/master/project-plans/451) Milestones dates were announced after we finished, so those will be updated.

**Comment by findikbey** [comment]
Project plan is updated according to given customer milestone dates.

**Comment by kayacanv** [comment]
every team updated their part, I think time to time it may need an update but currently I am closing the issue. Because All the teams did the full review
