### ISSUE TITLE
Review the requirements

### ISSUE THREAD

**Issue by emrehoser** [bounswe/bounswe2020group5#107]

**Comment by misraya** [comment]
I reviewed the requirements and corrected some typos.

**Comment by volkanbulca** [comment]
Under 1.1.2 User Interactions part of the requirements, some references were wrongly written so I corrected them.

**Comment by kayacanv** [comment]
Lastly we will ask guest user requirements to customer. So we are waiting for an answer right now.

**Comment by emrehoser** [comment]
I added 1.1.1.1.4 requirement.

**Comment by kayacanv** [comment]
I think it is okay #174
