### ISSUE TITLE
Deciding the coding convention for Back-end

### ISSUE THREAD

**Issue by sarismet** [bounswe/bounswe2020group5#117]
We need to decide the structure of our coding convention.

**Comment by sertayy** [comment]
The project initialization was completed at today's meeting, which was held between 14-14.30.

**Comment by sertayy** [comment]
I suggest you to use [PEP-8 rules](https://realpython.com/python-pep8/) for coding convention. I also suggest [Pylint](https://www.pylint.org/) which very useful in detecting errors and checking the readability of your code.

**Comment by thehalas** [comment]
I definitely agree on following PEP8.
