### ISSUE TITLE
mile1/ add changed project requirements to project report

### ISSUE THREAD

**Issue by ramizdundar** [bounswe/bounswe2020group5#174]
This should be done by everyone. Everybody should reply with their changed requirements and add them to both wiki and overleaf if it's already not done.

**Comment by ramizdundar** [comment]
Done.

**Comment by misraya** [comment]
I updated the following requirements to include more detail. 
* **1.1.2.1. Rating**
  * **1.1.2.1.1.** Users shall be able to rate the products they bought, out of 5.
  * **1.1.2.1.2.** Users shall be able to rate the vendors whom they bought a product from, out of 10.

**Comment by kayacanv** [comment]
it is updated and sent to Meric
