### ISSUE TITLE
Determining the logo of the project

### ISSUE THREAD

**Issue by sarismet** [bounswe/bounswe2020group5#22]
We need to find a cool logo for our project.

**Comment by kayacanv** [comment]
any idea? or is anybody know something about design?

**Comment by sarismet** [comment]
I think it is not something we can do just in a week. We need to discuss it more

**Comment by thehalas** [comment]
I made a prototype. If you all agree this could be our logo, at least for now.

<img src="https://raw.githubusercontent.com/bounswe/bounswe2020group5/master/mockup-image/bupazar_logo.png"  height = "200"/>

**Comment by sarismet** [comment]
It looks perfect. Well done

**Comment by emrehoser** [comment]
![Bupazar Logo](https://user-images.githubusercontent.com/44062306/77895660-c8976700-727f-11ea-9fe8-0c81613524e7.png)

I create a logo.
