### ISSUE TITLE
mobile/Implementing user setting page

### ISSUE THREAD

**Issue by yscaliskan** [bounswe/bounswe2020group5#220]
Users should be able to change their email address, password, name, and address data

**Comment by sertayy** [comment]
I have started working on this [issue](https://github.com/bounswe/bounswe2020group5/issues/261). So it can be closed. We can collaborate on [this](https://github.com/bounswe/bounswe2020group5/issues/261#issuecomment-751411762).

**Comment by sertayy** [comment]
Completed.
