### ISSUE TITLE
backend/ Credit card information, Ordering and payment functionality

### ISSUE THREAD

**Issue by volkanbulca** [bounswe/bounswe2020group5#228]
The following functionalities should be implemented:

- [x] Credit card information
- [x] Ordering Products
- [x] Order Status
- [x] Cancel order for both vendor and customer
- [x] Payment of the order
- [x] Important!: When payment is implemented, comment functionality must be updated.

Deadline: 27.12.2020 @20.00

**Comment by volkanbulca** [comment]
Credit card model is created. Functions for adding, deleting and getting credit card information are implemented.

**Comment by yusufyuksel96** [comment]
Order model is created. Order cancellation for both vendor and customer are implemented.

**Comment by volkanbulca** [comment]
Purchase model is created. make_purchase function is implemented.

**Comment by volkanbulca** [comment]
Status update functionality is implemented with supporting serializers and functions. Comment functionality is updated so that customers can comment on the products which they have purchased.
