### ISSUE TITLE
Developing our agenda and wiki sidebar.

### ISSUE THREAD

**Issue by sarismet** [bounswe/bounswe2020group5#24]

**Comment by sarismet** [comment]
I added some emojis to our wiki-side bar. I hope you enjoy it. I will close this issue in 2 hours if you don't have any suggestion.

**Comment by thehalas** [comment]
Nice emojis 😄, you didn't close the issue though.

**Comment by thehalas** [comment]
I had previously made the group members part collapsible on the sidebar I thought this comment belonged here.

**Comment by sarismet** [comment]
I decided not to close this issue until your comments come up and as your recommendation, I think the current version look good to me so I vote for leaving like this but others must say their own thoughts too.
