### ISSUE TITLE
Fixing the requirements page according to the feedback

### ISSUE THREAD

**Issue by thehalas** [bounswe/bounswe2020group5#28]
Everyone should fix their parts of the requirement page according to feedback given by the customer.

Log in to your Piazza to see the feedback.
Link :
[https://piazza.com/class/k5z7hzm7ncm1m3?cid=33](https://piazza.com/class/k5z7hzm7ncm1m3?cid=33)

**Comment by thehalas** [comment]
If you don't have a part, or you fixed your part, remove yourself from the assignees. If you are the last person assigned this issue, then close the issue.

**Comment by misraya** [comment]
There is no feedback related to my part. Still, I have some questions that will be clear after our meeting with the customer. I will update my part according to that.

**Comment by findikbey** [comment]
Outline of the requirements is edited. Protocol and ethical issues are moved to nonfunctional requirements part.

**Comment by sarismet** [comment]
non-functional requirements section should be enlarged (availability, security, etc.).

**Comment by volkanbulca** [comment]
Security section of the system requirements under functional requirements are fixed.

**Comment by sertayy** [comment]
1.1.1.1.1 and 1.1.1.1.3 sections are fixed.
