### ISSUE TITLE
backend/ bug : reset_password endpoint

### ISSUE THREAD

**Issue by kayacanv** [bounswe/bounswe2020group5#284]
Given:
{
  "email": "not_an_email"
}

Response:
<img width="561" alt="Screen Shot 2020-12-28 at 15 12 25" src="https://user-images.githubusercontent.com/25818997/103213558-192b1600-491f-11eb-837f-02936d427ef0.png">

It is not a bug but this response not a good example error field is inside the email which is array?.. also it will be better if you rename this as an error.
for example correct response

code 404 (<not found)
{
    "error" :  "not_registered"
}

**Comment by sarismet** [comment]
Done
