### ISSUE TITLE
Creating scenario 2, (Case About Adding Products)

### ISSUE THREAD

**Issue by kayacanv** [bounswe/bounswe2020group5#30]
Scenario Case About Adding Products will be written by  Muhammed Halas, Yaşar Selçuk Çalışkan, Kayacan Vesek
Do not forget clearly describing:
– The user and their role
– Preconditions
– Specific actions to achieve a desired goal
– Acceptance criteria

Deadline 02.03.2020

**Comment by thehalas** [comment]
I wrote the scenario.
The mocks still need to be added. 
Feel free to edit in any missing parts if you notice.  
[LINK](https://github.com/bounswe/bounswe2020group5/wiki/Scenario-2)

**Comment by kayacanv** [comment]
mockups are added may need review, I am clossing the issue
