### ISSUE TITLE
mile2/ Unit Tests

### ISSUE THREAD

**Issue by yusufyuksel96** [bounswe/bounswe2020group5#315]
* Each team member should explain the unit tests committed by him/her by referring to the commit SHA.
Deadline 05.01.2020 @19:00

**Comment by volkanbulca** [comment]
I added my unit tests to tests folder and explained them in milestone-2 report.

**Comment by sarismet** [comment]
I also added my unit tests and wrote the explanation of them in milestone-2 report.
