### ISSUE TITLE
Create Mockups of Customer Scenario: Ask to Vendor

### ISSUE THREAD

**Issue by misraya** [bounswe/bounswe2020group5#35]
Pages needed: 
- login
- home page
- search result & sorted
- product page + comments
- send a message to seller
- message sent pop up

- home page, my account-> messages
- select message, read reply

**Comment by misraya** [comment]
Login page is made on Thursday meeting. 
I made the mockups of **search result & sorted** and **product page + comments** , you can check them on Balsamiq and make modifications if you want to.

**Comment by findikbey** [comment]
**send a message to seller**, **message sent pop up**, my account->messages**, **read reply** mock ups are created, modifications can be made on Balsamiq.
