### ISSUE TITLE
Document Customer Scenario: Ask to Vendor

### ISSUE THREAD

**Issue by misraya** [bounswe/bounswe2020group5#36]
Persona, storyline and needed mockup pages are decided on Thursday meeting. 
Document the scenario with screenshots on Wiki, after mockups are done.

**Comment by findikbey** [comment]
Persona is described in Scenario 3 wiki page. Additions can be done later on.

**Comment by misraya** [comment]
Acceptance Criteria and Scenario sections are added. 
Documentation of the scenario 3 is completed.
Mockups will be added after they are completely done.
