### ISSUE TITLE
Deletion of unused/unnecessary branches.

### ISSUE THREAD

**Issue by sertayy** [bounswe/bounswe2020group5#368]
It would be better if the unused branches are deleted.

**Comment by misraya** [comment]
Good idea. It is becoming challenging to follow and switch between branches

**Comment by sertayy** [comment]
I deleted the unused branches I created previously.

**Comment by yusufyuksel96** [comment]
Done.

**Comment by sertayy** [comment]
All mobile related branches are cleaned except "mobile" branch.
