### ISSUE TITLE
Organizing the .md files

### ISSUE THREAD

**Issue by thehalas** [bounswe/bounswe2020group5#38]
### Change existing links to the pages with the new ones.
- Members folder
- Meetings folder
- Scenarios folder
.
.
.

**Comment by kayacanv** [comment]
I think this issue overlaps with #52

**Comment by thehalas** [comment]
They certainly have an intersection part. You have my full consent to whatever you want to do about this subject.

**Comment by thehalas** [comment]
This issue will continue being handled in #52. Issue closed
