### ISSUE TITLE
Research : E-Commerce Websites

### ISSUE THREAD

**Issue by thehalas** [bounswe/bounswe2020group5#39]
Visiting some well-known e-commerce sites.
Some Links : 
[hepsiburada](https://www.hepsiburada.com/)
[trendyol](https://www.trendyol.com/)
[n11](https://www.n11.com/)
[gittigidiyor](https://www.gittigidiyor.com/)

**Comment by kayacanv** [comment]
[decathlon](https://www.decathlon.com.tr/) : I think it is pleasing to the eye, and easy to use website

**Comment by sarismet** [comment]
[Hepsiburada](https://www.hepsiburada.com/) it also looks nice and meets all the requirements

**Comment by kayacanv** [comment]
I think we have pass this stage, so I am closing

**Comment by emrehoser** [comment]
[trendyol](https://www.trendyol.com/) is a good example for the e-commerce site and mobile app.
