### ISSUE TITLE
mile3/ Mobile User Manual Documentation

### ISSUE THREAD

**Issue by sertayy** [bounswe/bounswe2020group5#407]
User manual documentation task distribution listed below. 
Sertay: 
- [x] Chat
- [x] Favorite List
- [x] Categories & Subcategories
- [x] Change Password
- [x] Edit Personal Information
- [x] Logout

Yaşar:
- [x] Cart 
- [x] Vendor Order
- [x] Customer Order

Emre:
- [x] Verification Page
- [x] Forgot Password
- [x] Guest

Kayacan:
- [x] Add Product

**Comment by kayacanv** [comment]
this is done, added to deliverables
