### ISSUE TITLE
About Mobile Application

### ISSUE THREAD

**Issue by mericturan** [bounswe/bounswe2020group5#417]
Dear Android developers,

Can one or more of you attend an online meeting and provide some guidance to me about your Android application tomorrow (February 3, Wednesday)?

If so, I am open for time suggestions.

**Comment by sertayy** [comment]
Hi Meric, 

Sorry for the late response. What about 1 PM?

Thanks.

**Comment by mericturan** [comment]
Unfortunately, 1 pm is not OK for me. Can we say 2 pm?

**Comment by kayacanv** [comment]
2pm is okay for us

**Comment by mericturan** [comment]
Great. We will use the following Google Meet link for the meeting: https://meet.google.com/qtp-yexh-vqt.

**Comment by mericturan** [comment]
Thanks for your participation.
