### ISSUE TITLE
Orientation for Emre

### ISSUE THREAD

**Issue by mericturan** [bounswe/bounswe2020group5#49]
Dear @kayacanv,

Can you help and guide @Physicliar during his catch up period to our course?

Also, @Physicliar, can you state your name in your [GitHub account](https://github.com/Physicliar) so that everyone can easily find out that you are Emre?

**Comment by kayacanv** [comment]
Hi I talked to Emre, 
and I give superficial information about the group. In the next meeting he will meet others and the orientation process will be over.
Again welcome to our team @Physicliar .
