### ISSUE TITLE
Class Diagram updated according feedback

### ISSUE THREAD

**Issue by kayacanv** [bounswe/bounswe2020group5#50]
Kayacan, Volkan, İsmet will be designing Designing class diagram
Deadline: 8.04.2020

**Comment by kayacanv** [comment]
@volkanbulca @sarismet  I think we are done at here?
@sarismet İf you updated, could you close the issue?

**Comment by sarismet** [comment]
As you mention we are done. I will close it in a minute.

**Comment by sarismet** [comment]
is it okey for you @volkanbulca

**Comment by volkanbulca** [comment]
I think it is okay now. I have just recently added and modified some classes' fields and methods.
@sarismet can you please update the class diagram with the most recent one.

**Comment by sarismet** [comment]
Updated.

**Comment by sarismet** [comment]
We are done.
