### ISSUE TITLE
Sequence Diagrams will be created and updated

### ISSUE THREAD

**Issue by kayacanv** [bounswe/bounswe2020group5#51]
Halas, Sertay, Yaşar, Emre will be designing sequence diagrams.
Deadline: 12.04.2020

**Comment by emrehoser** [comment]
Vendor add new product sequence diagram is added in wiki page.

**Comment by sertayy** [comment]
Add to chart sequence diagram is added.

**Comment by yscaliskan** [comment]
added create chat and create comment sequence diagrams

**Comment by sertayy** [comment]
Remove to chart sequence diagram is added.

**Comment by emrehoser** [comment]
Customer Cancel an Order sequence diagram is added.
