### ISSUE TITLE
Designing RAM 

### ISSUE THREAD

**Issue by sarismet** [bounswe/bounswe2020group5#54]

**Comment by sarismet** [comment]
I personally have written the lines 56-77 of RAM.

**Comment by emrehoser** [comment]
I design the title color and wrote the lines 33-56.

**Comment by volkanbulca** [comment]
I completed the **Project Repository** and **Requirements** parts of the RAM.

**Comment by thehalas** [comment]
I was the 4th member assigned to this issue. I did the rest of the work. 
Other groups members are encouraged to review the RAM to make sure it is complete.

**Comment by kayacanv** [comment]
close this issue please, if it's done.  Seems like done :dancers:

**Comment by volkanbulca** [comment]
It is done for sure 👍
