### ISSUE TITLE
Milestone 1 - Report

### ISSUE THREAD

**Issue by misraya** [bounswe/bounswe2020group5#58]
Each member should complete their part of the report. After that, please leave a comment regarding your contribution and remove yourselves from assignees.

**Comment by misraya** [comment]
Evaluation of tools and my personal contribution summary is added.

**Comment by findikbey** [comment]
Preparation of the table work done by each member  is completed.

**Comment by sertayy** [comment]
My personal contribution summary is added

**Comment by Physicliar** [comment]
My personal contribution moving forward is added.

**Comment by sarismet** [comment]
My personal contribution is completed.

**Comment by volkanbulca** [comment]
I added my personal contribution summary part to the table.

**Comment by sertayy** [comment]
I added the [project status](https://github.com/bounswe/bounswe2020group5/wiki/Milestone-1-Report) to milestone 1 report.

**Comment by volkanbulca** [comment]
I added the project description part to the [Milestone 1 Report](https://github.com/bounswe/bounswe2020group5/wiki/Milestone-1-Report).

**Comment by emrehoser** [comment]
I added my personal contribution to the table.

**Comment by emrehoser** [comment]
- I added my personal contribution to the table.
- I created deliverables tables.

**Comment by kayacanv** [comment]
merged the content, uploaded report file to Moodle and Github.

Now that we're done :+1:
