### ISSUE TITLE
Description of APIs introduced

### ISSUE THREAD

**Issue by misraya** [bounswe/bounswe2020group5#84]
Please briefly explain the functionality of your endpoint [here](https://github.com/bounswe/bounswe2020group5/wiki/Description-of-APIs-introduced). 
Those who completed can remove themselves from assignees.

**Comment by misraya** [comment]
Created the page and added my part.

**Comment by sertayy** [comment]
I explained my part.

**Comment by findikbey** [comment]
I described the endpoint I implemented.

**Comment by yscaliskan** [comment]
I explained my part.

**Comment by volkanbulca** [comment]
I added my part.

**Comment by emrehoser** [comment]
I have done my part

**Comment by Physicliar** [comment]
I have done my part

**Comment by sarismet** [comment]
I have done my part

**Comment by thehalas** [comment]
I have done my part
